name: Deploying to Production
on:
  pull_request:
    branches:
      - production
    types:  [closed]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGE_HOST }}
          username: ${{ secrets.STAGE_USERNAME }}
          key: ${{ secrets.STAGE_KEY }}
          script: sh /deploy/${{secrets.DEPLOY_SCRIPT}}.sh
